// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string    `json:"text"`
	UserID string    `json:"userId"`
	List   []*string `json:"list"`
}

type Todo struct {
	ID   string    `json:"id"`
	Text string    `json:"text"`
	User *User     `json:"user"`
	List []*string `json:"list"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
